# Generated by Django 6.1.1 on 2026-09-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SessionClass',
            fields=[
                ('session_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('row_index', models.IntegerField()),
                ('game_status', models.CharField(choices=[('in_progress', 'În progres'), ('win', 'Câștig'), ('lose', 'Pierdere')])),
                ('current_date', models.DateTimeField()),
            ],
        ),
    ]
