# Generated by Django 6.1.1 on 2026-09-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_session', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionclass',
            name='current_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='sessionclass',
            name='game_status',
            field=models.CharField(choices=[('in_progress', 'În progres'), ('win', 'Câștig'), ('lose', 'Pierdere')], null=True),
        ),
        migrations.AlterField(
            model_name='sessionclass',
            name='row_index',
            field=models.IntegerField(null=True),
        ),
    ]
