# Generated by Django 6.1.1 on 2026-09-09 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words_operations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentRowIndex', models.IntegerField()),
                ('status', models.CharField(choices=[('in_progress', 'În progres'), ('win', 'Câștig')])),
            ],
        ),
        migrations.AlterModelOptions(
            name='wordclass',
            options={'managed': False},
        ),
    ]
