# Generated by Django 6.1.1 on 2026-09-12 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words_operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wordclass',
            options={'managed': False},
        ),
    ]
