# Generated by Django 6.1.1 on 2026-09-12 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words_operations', '0002_alter_wordclass_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='wordclass',
            table='words',
        ),
    ]
