# Generated by Django 6.1.1 on 2026-09-12 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words_operations', '0003_sessionclass_delete_gamestate_alter_wordclass_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SessionClass',
        ),
    ]
